import { Header } from '@/components/Header';
import { i18nConfig, Locale } from '@/i18n-config';
import { getAlternateLanguages } from '@/lib/i18n/get-alternate-languages';
import { getGlobal } from '@/services/global';
import { Metadata } from 'next';
import { notFound } from 'next/navigation';

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> {
	const { locale } = await params;
	const global = await getGlobal(locale);

	const localizedUrl = getAlternateLanguages()[locale];
	const title = global?.defaultCeo?.metaTitle ?? global?.siteName ?? `Nextvibe - ${locale.toUpperCase()}`;
	const description =
		global?.defaultCeo?.metaDescription ?? global?.siteDescription ?? 'Generated by create next app';

	const shareImage = global?.defaultCeo?.shareImage ? global?.defaultCeo?.shareImage.url : 'nextvibe-og-image.png';

	return {
		metadataBase: localizedUrl,
		title,
		description,
		authors: [{ name: 'NextVibe', url: localizedUrl }, { name: 'Dejan Vjestica' }],
		openGraph: {
			title,
			description,
			url: localizedUrl,
			images: [shareImage],
			type: 'website',
		},
		twitter: {
			card: 'summary_large_image',
			title,
			description,
			images: [shareImage],
		},
		icons: {
			icon: [
				{ url: '/favicon.ico' },
				{
					url: '/favicon-16x16.png',
					sizes: '16x16',
					type: 'image/png',
				},
				{
					url: '/favicon-32x32.png',
					sizes: '32x32',
					type: 'image/png',
				},
			],
			apple: [
				{
					url: '/apple-touch-icon.png',
					sizes: '180x180',
				},
			],
			other: [
				{
					rel: 'icon',
					url: '/android-chrome-192x192.png',
					sizes: '192x192',
				},
				{
					rel: 'icon',
					url: '/android-chrome-512x512.png',
					sizes: '512x512',
				},
			],
		},
		other: {
			'google-site-verification': 'TACl-_054sHbqAorEk_zLqODN4vohWKcIw3RFBUE-84',
		},
		alternates: {
			canonical: localizedUrl,
			languages: {
				...getAlternateLanguages(),
				'x-default': localizedUrl,
			},
		},
	};
}

export async function generateStaticParams() {
	return i18nConfig.locales.map((locale) => ({ locale }));
}

export default async function LocaleLayout({
	children,
	params,
}: {
	children: React.ReactNode;
	params: Promise<{ locale: string }>;
}) {
	const { locale } = await params;

	if (!i18nConfig.locales.includes(locale as Locale)) {
		notFound();
	}

	return (
		<>
			<Header locale={locale as Locale}></Header>
			{children}
		</>
	);
}
