import { Header } from "@/components/Header";
import { i18nConfig } from "@/i18n-config";
import { getGlobal } from "@/services/global";
import { Metadata } from "next";
import { notFound } from "next/navigation";

export async function generateMetadata({ params }: { params: Promise<{ locale: string }> }): Promise<Metadata> {
  const { locale } = await params;
  const global = await getGlobal(locale);
  const baseUrl = process.env.NEXT_PUBLIC_SITE_URL ?? (process.env.NODE_ENV === "development" ? `http://localhost:${process.env.PORT || 3000}` : undefined);

  if (!baseUrl) {
    throw new Error("NEXT_PUBLIC_SITE_URL is not defined and NODE_ENV is not development.");
  }

  const metadataBase = new URL(baseUrl);
  const title = global?.defaultCeo?.metaTitle ?? global?.siteName ?? `Nextvibe - ${locale.toUpperCase()}`;
  const description = global?.defaultCeo?.metaDescription ?? global?.siteDescription ?? "Generated by create next app";

  const shareImage = global?.defaultCeo?.shareImage ? global?.defaultCeo?.shareImage.url : "nextvibe-og-image.png";
  const canonicalUrl = locale === "de" ? "" : "/de";

  return {
    metadataBase,
    title,
    description,
    authors: [{ name: "NextVibe", url: metadataBase }, { name: "Dejan Vjestica" }],
    openGraph: {
      title,
      description,
      url: metadataBase.toString(),
      images: [shareImage],
      type: "website",
    },
    twitter: {
      card: "summary_large_image",
      title,
      description,
      images: [shareImage],
    },
    icons: {
      icon: [{ url: "/favicon.ico" }, { url: "/favicon-16x16.png", sizes: "16x16", type: "image/png" }, { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" }],
      apple: [{ url: "/apple-touch-icon.png", sizes: "180x180" }],
      other: [
        { rel: "icon", url: "/android-chrome-192x192.png", sizes: "192x192" },
        { rel: "icon", url: "/android-chrome-512x512.png", sizes: "512x512" },
      ],
    },
    other: {
      "google-site-verification": "TACl-_054sHbqAorEk_zLqODN4vohWKcIw3RFBUE-84",
    },
    alternates: {
      canonical: `${canonicalUrl}`,
      languages: {
        en: "/en",
        de: "/",
        "x-default": "/",
      },
    },
  };
}

export async function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

export default async function LocaleLayout({ children, params }: { children: React.ReactNode; params: Promise<{ locale: string }> }) {
  const { locale } = await params;

  if (!i18nConfig.locales.includes(locale as "de" | "en")) {
    notFound();
  }

  return (
    <>
      <Header></Header>
      {children}
    </>
  );
}
